package com.beseech.model;

import java.util.List;

public class Organization {
    private String _id;
    private String _subdomain;
    private String _name;
    private Boolean _isAutogenerated;
    private List<String> _emailDomains;

    public String getId() {
        return _id;
    }

    public void setId(String id) {
        _id = id;
    }

    public String getSubdomain() {
        return _subdomain;
    }

    public void setSubdomain(String subdomain) {
        _subdomain = subdomain;
    }

    public String getName() {
        return _name;
    }

    public void setName(String name) {
        _name = name;
    }

    public Boolean getAutogenerated() {
        return _isAutogenerated;
    }

    public void setAutogenerated(Boolean autogenerated) {
        _isAutogenerated = autogenerated;
    }

    public List<String> getEmailDomains() {
        return _emailDomains;
    }

    public void setEmailDomains(List<String> emailDomains) {
        _emailDomains = emailDomains;
    }
}
